[#19] Create and clean common directory
hanseulhee/OnsuYumYumi pull request #20
Opened 2022-02-27 16:54 UTC by hanseulhee

### 설명

재사용 가능한 컴포넌트들을 components/common 디렉토리에 정리하였습니다.

### 중점적으로 봐줬으면 좋을 부분

2022-02-27 20:09 UTC, hyesungoh requested changes

2022-02-27 20:09 UTC, hyesungoh commented on src/pages/Main/index.tsx
> +import Line from "../../components/common/Line";
해당 부분 `절대 주소`로 변경해주시면 좋을 거 같아요 ~~! 💟

2022-02-28 02:57 UTC, hanseulhee commented on src/pages/Main/index.tsx
> +import Line from "../../components/common/Line";
😊💛

2022-02-28 07:11 UTC, hyesungoh approved these changes
👍 🥇 🐖

2022-02-28 07:12 UTC, merged